version: '3.1'

services:
  app:
    build:
      context: ./docker
      dockerfile: app.dockerfile
    ports: 
      - 8000:8000
  drupal:
    image: drupal:10-apache
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: postgres
    restart: always
    ports:
      - 5432:5432